### ISSUE TITLE
Serialize edge as pair of (node, option[port])

### ISSUE THREAD

**Issue by ss2165** [CQCL-DEV/hugr#133]
### Discussed in https://github.com/CQCL-DEV/hugr/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **ss2165** May 30, 2023</sup>
In the serialization spec currently all edges are defined as pairs of (node, port). However in the main spec ports are only used for input/const_input/output

I propose instead to move to pairs of (node, Option[port]) such that control flow edges can be expressed as ((node, port), (node, null)) and order edges as ((node, null), (node, null)).

@mark-koch does that work for guppy?</div>

**Comment by aborgna-q** [comment]
Implementing this should probably wait for #130 first.
