### ISSUE TITLE
Rename `NotADag`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL-DEV/hugr#137]
Validation can fail for reasons other than not being a directed acyclic graph, so the name is misleading. Perhaps `InvalidGraph`?

**Comment by aborgna-q** [comment]
That's a bug in the Dag checker 😅 . I have a fix in the works.

**Comment by cqc-alec** [comment]
If it's a bug in the DAG checker then it's also a documentation bug:

```rust
    #[error("The children of an operation {optype:?} must form a dag with single source and sink. Loops are not allowed, nor are dangling nodes not in the path between the input and output. In node {node:?}.")]
    NotADag { node: Node, optype: OpType },
```

(The docs already imply that there are more conditions than not being a DAG.)

**Comment by aborgna-q** [comment]
The "single source and sink" requirement is an special kind of DAG. I think we are still in the `NotADag` category, and the user should be able to see the docs or the error message with the specific info.

**Comment by cqc-alec** [comment]
Just seems odd to get an error called `NotADag` for something that is in fact a DAG, just not the right kind of DAG.

**Comment by cqc-alec** [comment]
Hmm...

https://cs.stackexchange.com/questions/67849/what-do-you-call-a-dag-with-a-single-root-source

How about `NotABoundedDAG`? "Bounded" because if we interpret it as a poset then it has a maximal and a minimal element?
