### ISSUE TITLE
Dot string visualisation draws unconnected ports for StateOrder

### ISSUE THREAD

**Issue by ss2165** [CQCL-DEV/hugr#160]
So all nodes have extra unconnected ports
I believe this is due to changes from #152 
![image](https://github.com/CQCL-DEV/hugr/assets/12997250/d82ebec2-d801-4a87-9a69-af4f02f88112)

**Comment by ss2165** [comment]
Ideal behaviour: ignore unconnected StateOrder ports

**Comment by aborgna-q** [comment]
It should easy to solve once this is merged. https://github.com/CQCL/portgraph/pull/69
