### ISSUE TITLE
Add appendix listing all node types and edge constraints

### ISSUE THREAD

**Issue by cqc-alec** [CQCL-DEV/hugr#165]
There are some node types currently not included in it:

- `Const`
- `Call`
- `LoadConst`
- `Declare`
- `AlisasDeclare`
- `AliasDef`

(Also `CallIndirect` but this should probably move to the Tierkreis/higher-order resource; see #154 .)

**Comment by ss2165** [comment]
That table is only for containers, note all of these are non-container operations, they should be covered by _O_. If not, _O_ needs redefining to be more general.

**Comment by cqc-alec** [comment]
OK yes. I think a super-table listing all node types and the constraints on edge types between them would be useful.

**Comment by ss2165** [comment]
Perhaps an appendix item?
