### ISSUE TITLE
Compact nodes in `HugrMut`

### ISSUE THREAD

**Issue by aborgna-q** [CQCL-DEV/hugr#208]
Or something similar, to ensure that a serialization roundtrip won't modify the node indices.

(Also requires making the root the first node)

**Comment by ss2165** [comment]
maybe `canoncalize_nodes` ?

**Comment by aborgna-q** [comment]
Relevant portgraph PR
https://github.com/CQCL/portgraph/pull/83

**Comment by lmondada** [comment]
+1 for this, it would be good if serialisation and compact nodes were separate. I have bugs that I am tracking down that depend on node indices. Currently those bugs disappear once the hugr instances are serialised...
