### ISSUE TITLE
Quantum Opaque Types (in Resources)

### ISSUE THREAD

**Issue by acl-cqc** [CQCL-DEV/hugr#222]
The spec defines both Opaque types (which are Classic) and QPaque (which are linear, i.e. non-classic). So, we should have some syntax in the YAML (and, following #186, we'll need to add some support in the Rust Hugr codebase) for both linear and classic type definitions (including parameterized).

It seems reasonable that any type that instantiates a TypeDef with linear type arguments (e.g., `MyList<Qubit>`) must be linear. But new TypeDef's can also be linear (i.e., fail to be copyable) regardless of any type arguments; for example `MyNewQubit`, `Qudit` or the polymorphic definition `Quxit<Int>` (which gives rise to types `Quxit<3>` and `Quxit<8>`).

**Comment by ss2165** [comment]
Outdated, covered by `TypeDefBound` etc.
