### ISSUE TITLE
Container factory methods - new_array

### ISSUE THREAD

**Issue by acl-cqc** [CQCL-DEV/hugr#288]
We have `new_tuple` and `new_sum`; following #287 it may be that `new_array` is the only one we need, but nonetheless it'd be good to have so that we always end up with `SimpleType::Classic(ClassicType::Container(Container::Array(clas_ty, sz)))` rather than `SimpleType::Qontainer(Container::Array(SimpleType::Classic(clas_ty), sz))`

**Comment by ss2165** [comment]
As of #378 this now belongs in the prelude

**Comment by ss2165** [comment]
Made obsolete by #378
