### ISSUE TITLE
[Big Refactor]Make Container contain single elements (?)

### ISSUE THREAD

**Issue by acl-cqc** [CQCL-DEV/hugr#290]
Rather than `SimpleType::Qontainer`, `ClassicType::Container` and `HashableType::Container`, instead make SimpleType/ClassicType/HashableType be aliases for Container<SimpleElem/ClassicElem/HashableElem> and add to Container an enum variant `Single(T)` (a single value).

This may not be a win, but will probably make more sense after #286 which takes us partway there, and solves the hack in `typecheck_const` that there are currently two ways to express the SimpleType that's (any container of) a ClassicType:
* `SimpleType::Classic(ClassicType::Container(Container::List(clas_ty)))`
* `SimpleType::Qontainer(Container::List(SimpleType::Classic(clas_ty)))`

Instead there would be only one way: `Container::List(Container::Single(SimpleElem::Classic(clas_ty)))`

**Comment by ss2165** [comment]
Done as part of #378
