### ISSUE TITLE
Mutable views

### ISSUE THREAD

**Issue by aborgna-q** [CQCL-DEV/hugr#293]
Allow mutable region views (and flat region views).

Along this, the internal `HugrMut` methods should be moved to a sealed trait, and make the regions implement the public `HugrMut`.

Then we can add https://github.com/CQCL-DEV/hugr/issues/246 to that public trait.

**Comment by acl-cqc** [comment]
@aborgna-q should I close this now? Or do we think we want a DescendantsMut enough to keep this open? (Maybe that should be a new issue?)

**Comment by aborgna-q** [comment]
Let's close this 👍
