### ISSUE TITLE
Add resources to validation context

### ISSUE THREAD

**Issue by ss2165** [CQCL-DEV/hugr#362]

**Comment by aborgna-q** [comment]
There are some missing resource validations:

1. Check that `NodeType`s for custom ops require the resource that defines the op.
2. Custom types in a custom op's signature should have "matching" resources. Here we may actually use types from resources that are imported by the op's resource...

Whether those resources are correctly propagated through the edges and hierarchy is already checked by @croyzor code.

- Item 1 is a simple check on the `ResourceId`s.
- Item 2 requires access to the actual `Resource`. This requires a reference to a "Resource Registrar", that we'll need to access at every place where we use `hugr.validate()`. I think defining the registrar is outside the scope of this Issue.

Am I missing other cases?

**Comment by acl-cqc** [comment]
Item 2 (defining a Resource Registrar/Registry) is totally what I was thinking of. It might start out just as a HashMap from string, though.

As you say, we'll need it *at every place where we use `hugr.validate()`. The frustrating one of these is in Builder `finish_hugr()` - the simple thing is probably to pass the extensions in there too, but a better idea might be for the Builder to build this set *as well*, or something like that. I think the latter can be a separate issue and I'll probably just pass the same map into `finish_hugr()`.

**Comment by acl-cqc** [comment]
Done by #467
