### ISSUE TITLE
Add instantiations of `OpDef`s

### ISSUE THREAD

**Issue by aborgna-q** [CQCL-DEV/hugr#88]
The custom operation definitions should be able to create new objects that implement the `CustomOp` trait.
We need to define that object and decide how to initialize from a definition.

**Comment by acl-cqc** [comment]
Is this handled by my #186 (where `CustomOp`, an OpType, is the instantiation of `OpDef`, which belongs to a Resource but is not an OpType) ? If so, we can assign this to me.

**Comment by aborgna-q** [comment]
Yes, I think that PR should cover this.
